### ISSUE TITLE
Collect Prometheus metrics in the runtime framework

### ISSUE THREAD

**Issue by lance** [openshift-cloud-functions/faas-js-runtime-image#18]
Expose these at `/metrics`

**Comment by slinkydeveloper** [comment]
I'm not sure the prometheus way to collect metrics does the job: since it's prometheus itself that does the scraping at a prefixed interval, if a function is bring down before the scraping happens, some informations (that could be relevant) are lost. Should we configure it to push metrics, like explained [here](https://prometheus.io/docs/instrumenting/pushing/)?

**Comment by slinkydeveloper** [comment]
Maybe should we have some metrics collector where we can push the informations (maybe we could do the same for logs)

**Comment by lance** [comment]
@slinkydeveloper after a brief conversation with @bbrowning I am going to close this. Since all functions are run as a Knative `Service`, a function developer can simply rely on the metrics that Knative itself collects, including latency, execution count, etc.
